### PR TITLE
Full Cotire Support

### PR DESCRIPTION
**Pull request by cwfitzgerald**
This is the examples equivalent to https://github.com/GameFoundry/bsf/pull/142.

It also adds basic travis support.

### CODE REVIEW

**Comment by BearishSun** [comment]
Do we need cotire for examples since they are only one source file?

Also I don't plan on setting up CI for examples at the moment, and when I do I'd like to somehow re-use the travis/appveyor for both projects so I don't need to maintain mostly duplicate code.

**Comment by cwfitzgerald** [comment]
I would argue yes, as we want people who are reading the examples to know that cotiring exists in the codebase and we have facilities to do that. People are much more likely to look at the examples then directly read the manual. We can remove cotire.cmake though.

That's also fine. 

It would probably be easier to just close this PR and you can put in cotire and the colored output thing.

**Comment by BearishSun** [comment]
Makes sense. I've enabled cotire on the relevant targets, and the rest of the changes should be inherited from the framework's cmake.

**Comment by cwfitzgerald** [comment]
Unfortunately you do need the colored output function call in the top level example cmake because the changes made don't propagate up subdirectories so the examples are left without color.
---
Connor Fitzgerald

**Comment by BearishSun** [comment]
I've moved that code into `Properties.cmake`, which gets included from the root `CMakeLists.txt` for examples, bsf and custom user projects. I haven't tested it but I think that should be fine?

**Comment by cwfitzgerald** [comment]
Ah yes, that's all good. Didn't see that, on mobile. 
---
Connor Fitzgerald

**Pull request closed without merging**
